/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // JUnit Jupiter test dependency (you can use other frameworks if you prefer)
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.2")
    testImplementation("org.mockito:mockito-core:3.+")

    // An api dependency is exported to consumers, that is to say found on their compile classpath.
//    api("")

    // An implementation dependency is used internally, and not exposed to consumers on their own compile classpath.
//    implementation("")
}

tasks.test {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
